spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/portafolio_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:180523}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

security:
  jwt:
    secret-key: ${JWT_SECRET:MTIzNDU2Nzg5MGFiY2RlZjEyMzQ1Njc4OTBhYmNkZWYxMjM0NTY3ODkwYWJjZGVm}
    expiration-time: 86400000

  cloudinary:
    cloud-name: wuenqpan
    api-key: 323679837997148
    api-secret: tPRBzE7HggsTRR6b2fxvl9-ASmo